In [2]:
import numpy as np

In [30]:
x_train = np.array([[1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
            [2.0, 4.0, 6.0, 8.0, 10.0, 12.0],
            [101.0, 201.0, 301.0, 401.0, 501.0, 601.0]])
y_train = np.array([10, 20, 30, 40, 50, 60])
#w = np.zeros(len(x_train[0]))
w=[11, 12, 13, 14, 15, 16]
print(x_train)
print(w)
b=10

[[  1.   2.   3.   4.   5.   6.]
 [  2.   4.   6.   8.  10.  12.]
 [101. 201. 301. 401. 501. 601.]]
[11, 12, 13, 14, 15, 16]


In [31]:
#calculating the formula
def myformula(x, w, b):
    f=np.dot(x, w) + b 
    return f
print(myformula(x_train, w, b))

[  311.   612. 30191.]


In [32]:
#calculating cost function
def costfunc(x, y, w, b,):
    m = x.shape[0]
    error = 0
    add = 0
    for i in range(m):
        error = (myformula(x, w, b) - y[i])**2
        add = add + error
        J = 1/((2*m)*add)
    return J
print(costfunc(x_train, y_train, w, b))
    

[6.55540828e-07 1.58489858e-07 6.10306582e-11]
